### ISSUE TITLE
Contracts roadmap

### ISSUE THREAD

**Issue by raysonkoh** [murcia-cs4215/ocontract#11]
- [x] Predicate contracts
- [x] Function contracts for first-order functions
- [x] Contracts for higher-order functions
- [x] In-built contracts (for commonly-used contracts)
- [x] Dependent contracts **(stretch)**
- [ ] Higher-order Contracts **(stretch)**
- [x] Allow functions that have a defined contract to take another function that has a defined contract as an argument, and also allow it to return functions with a defined contract **(stretch)**

**Comment by zhuhanming** [comment]
Ignore my previous response, the feature is fully implemented in #19

**Comment by zhuhanming** [comment]
In-built contracts/functions implemented in #24

**Comment by zhuhanming** [comment]
I realised we basically implemented everything except higher-order contracts (actually what classifies as higher-order contracts? maybe we unknowingly implemented it already haha)

**Comment by raysonkoh** [comment]
I was initially thinking of allowing composition of contracts to form new contracts, or having a generator function for contracts. But I think can ignore this as it doesn't really fit with our contracts system now.
